name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install express

    - name: Create shared folder
      run: mkdir -p ${{ github.workspace }}/shared_folder

    - name: copy node modules in github workspace
      run: cp -r node_modules ${{ github.workspace }}/shared_folder
    
    - name: copy node modules in github workspace
      run: cp -r package.json ${{ github.workspace }}/shared_folder
    
    - name: copy node modules in github workspace
      run: cp -r package-lock.json ${{ github.workspace }}/shared_folder


   
  runjob:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        host: localhost
        port: 3000
        timeout: 120

    - name: give me file
      run: ls

    - name: 'copy the files from github workspce'
      run: cp ${{ github.workspace }}/shared_folder .

    # - name: 'copy the files from github workspce'
    #   run: cp ${{ github.workspace }}/shared_folder .

    # - name: 'copy the files from github workspce'
    #   run: cp ${{ github.workspace }}/shared_folder .
  
    - name: Start the server
      run: |
          set -x
          node index.js & 
          echo "hi harsh"

    - name: Wait for server to start
      run: sleep 10
        

      


