name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install express
  runjob:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        host: localhost
        port: 3000
        timeout: 120
  
    - name: Start the server
      run: |
          node index.js & 
          echo "hi harsh"
          
    - name: Check if server is running
      run: |
          for i in $(seq 1 30); do
            curl -sS http://localhost:3000 >/dev/null && echo "Server is running" && exit 0
            sleep 5
          done
          echo "Server did not start" && exit 1

      


