name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install express
  runjob:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
  
    - name: Start the server
      run: |
          node index.js & 
          echo "hi harsh"
      with:
          host: localhost
          port: 3000
          timeout: 120
    - name: Check if server is running
      run: |
          if curl -IsS http://localhost:3000 | head -n 1 | grep -q 200; then
            echo "Server is running"
          else
            echo "Server has crashed"
            exit 1
          fi

      


